### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by flygohr** [teztok/8bidou-demo#1]
I have a 4k screen and it would be nice if the website could have a maximum width instead of being completely responsive - because now I'm seeing some gigantic pixels on my screen and 8bidous are really best looked at somewhat smaller :D apart from that, maybe loading the full inventories by default? Amazing website :D

**Comment by xat** [comment]
thanks for your input!

the maximum width problem is fixed now. loading the full inventory can be a bit much in some cases, but i doubled the number of items from 24 to 48.
